version: "3.11"
services:
  rag_api:
    build: .
    container_name: rag_api
    ports:
      - "80:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAISS_INDEX_FILE=/data/faiss_index.pkl
      - EMBEDDING_MODEL=text-embedding-3-small
    volumes:
      - ./data:/data
      - ./backend:/backend